package Vistas;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tomas
 */
public class FormIdiomas extends javax.swing.JFrame {

    /**
     * Creates new form FormIdiomas
     */
    public FormIdiomas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloMantenedorIdiomas = new javax.swing.JLabel();
        panelMI = new javax.swing.JPanel();
        lvlNombreIdiomaMI = new javax.swing.JLabel();
        fieldNombreIdiomaMI = new javax.swing.JTextField();
        btnINGRESARMI = new javax.swing.JButton();
        btnBUSCARMI = new javax.swing.JButton();
        btnVolverMI = new javax.swing.JButton();
        lblListadoIdiomasMI = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableIdiomasMI = new javax.swing.JTable();
        btnELIMINARMI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MANTENEDOR DE IDIOMAS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTituloMantenedorIdiomas.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTituloMantenedorIdiomas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/idiomas.png"))); // NOI18N
        lblTituloMantenedorIdiomas.setText("MANTENEDOR DE IDIOMAS");

        panelMI.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lvlNombreIdiomaMI.setText("Nombre Idioma :");

        btnINGRESARMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/log-in ESTE OCUPÉ.png"))); // NOI18N
        btnINGRESARMI.setText("INGRESAR");
        btnINGRESARMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINGRESARMIActionPerformed(evt);
            }
        });

        btnBUSCARMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/browse.png"))); // NOI18N
        btnBUSCARMI.setText("BUSCAR");
        btnBUSCARMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBUSCARMIActionPerformed(evt);
            }
        });

        btnVolverMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/regreso.png"))); // NOI18N
        btnVolverMI.setText("VOLVER AL MENÚ PRINCIPAL");
        btnVolverMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMILayout = new javax.swing.GroupLayout(panelMI);
        panelMI.setLayout(panelMILayout);
        panelMILayout.setHorizontalGroup(
            panelMILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMILayout.createSequentialGroup()
                        .addComponent(lvlNombreIdiomaMI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fieldNombreIdiomaMI, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMILayout.createSequentialGroup()
                        .addGroup(panelMILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnVolverMI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelMILayout.createSequentialGroup()
                                .addComponent(btnBUSCARMI, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnINGRESARMI, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelMILayout.setVerticalGroup(
            panelMILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlNombreIdiomaMI, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNombreIdiomaMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelMILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBUSCARMI)
                    .addComponent(btnINGRESARMI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolverMI)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblListadoIdiomasMI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblListadoIdiomasMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lista-de-quehaceres.png"))); // NOI18N
        lblListadoIdiomasMI.setText("LISTADO DE IDIOMAS");

        tableIdiomasMI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Idiomas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableIdiomasMI);

        btnELIMINARMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eliminar.png"))); // NOI18N
        btnELIMINARMI.setText("ELIMINAR");
        btnELIMINARMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnELIMINARMIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloMantenedorIdiomas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelMI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblListadoIdiomasMI)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnELIMINARMI, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblListadoIdiomasMI)
                    .addComponent(lblTituloMantenedorIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(btnELIMINARMI)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void btnELIMINARMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnELIMINARMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnELIMINARMIActionPerformed

    private void btnINGRESARMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINGRESARMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnINGRESARMIActionPerformed

    private void btnBUSCARMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBUSCARMIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBUSCARMIActionPerformed

    private void btnVolverMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMIActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverMIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIdiomas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormIdiomas().setVisible(true);
            }
        });
    }
    
        public void cerrar()
    {
        int resp=JOptionPane.showConfirmDialog(null,"¿Esta seguro/a que desea cerrar la ventana de Idioma?","Confirmación de Cierre",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(resp==JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBUSCARMI;
    private javax.swing.JButton btnELIMINARMI;
    private javax.swing.JButton btnINGRESARMI;
    private javax.swing.JButton btnVolverMI;
    private javax.swing.JTextField fieldNombreIdiomaMI;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblListadoIdiomasMI;
    private javax.swing.JLabel lblTituloMantenedorIdiomas;
    private javax.swing.JLabel lvlNombreIdiomaMI;
    private javax.swing.JPanel panelMI;
    private javax.swing.JTable tableIdiomasMI;
    // End of variables declaration//GEN-END:variables
}
