package Vistas;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tomas
 */
public class FormVenderLibros extends javax.swing.JFrame {

    /**
     * Creates new form FormVenderLibros
     */
    public FormVenderLibros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloMantenedorVentas = new javax.swing.JLabel();
        lblDatosCompradorMV = new javax.swing.JLabel();
        lvlNombreMV = new javax.swing.JLabel();
        lblApellidoPaternoMV = new javax.swing.JLabel();
        lblApellidoMaternoMV = new javax.swing.JLabel();
        lblRUTMV = new javax.swing.JLabel();
        lblTelefonoMV = new javax.swing.JLabel();
        lblDireccionMV = new javax.swing.JLabel();
        fieldNombreMV = new javax.swing.JTextField();
        fieldApellidoPaternoMV = new javax.swing.JTextField();
        fieldApellidoMaternoMV = new javax.swing.JTextField();
        fieldRUTMV = new javax.swing.JTextField();
        fieldTelefonoMV = new javax.swing.JTextField();
        fieldDireccionMV = new javax.swing.JTextField();
        lblCantidadMV = new javax.swing.JLabel();
        fieldCantidadMV = new javax.swing.JTextField();
        lblFormaDePagoMV = new javax.swing.JLabel();
        comboBoxFormaPagoMV = new javax.swing.JComboBox<>();
        lblTituloMV = new javax.swing.JLabel();
        lblCarritoMV = new javax.swing.JLabel();
        lblPrecioMV = new javax.swing.JLabel();
        fieldPrecioMV = new javax.swing.JTextField();
        btnGenerarOrdenMV = new javax.swing.JButton();
        comboBoxTituloMV = new javax.swing.JComboBox<>();
        btnVolverMV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VENTA DE LIBROS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTituloMantenedorVentas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloMantenedorVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dinero.png"))); // NOI18N
        lblTituloMantenedorVentas.setText("MANTENEDOR DE VENTAS");

        lblDatosCompradorMV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDatosCompradorMV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/comprador.png"))); // NOI18N
        lblDatosCompradorMV.setText("DATOS DEL COMPRADOR");

        lvlNombreMV.setText("Nombre:");

        lblApellidoPaternoMV.setText("Apellido Paterno:");

        lblApellidoMaternoMV.setText("Apellido Materno:");

        lblRUTMV.setText("RUT:");

        lblTelefonoMV.setText("Teléfono:");

        lblDireccionMV.setText("Dirección:");

        lblCantidadMV.setText("Cantidad:");

        fieldCantidadMV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCantidadMVActionPerformed(evt);
            }
        });

        lblFormaDePagoMV.setText("Forma de pago:");

        comboBoxFormaPagoMV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTituloMV.setText("Título:");

        lblCarritoMV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCarritoMV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ventas.png"))); // NOI18N
        lblCarritoMV.setText("CARRITO");

        lblPrecioMV.setText("Precio:");

        btnGenerarOrdenMV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/orden.png"))); // NOI18N
        btnGenerarOrdenMV.setText("GENERAR ORDEN DE COMPRA");
        btnGenerarOrdenMV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarOrdenMVActionPerformed(evt);
            }
        });

        comboBoxTituloMV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnVolverMV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/regreso.png"))); // NOI18N
        btnVolverMV.setText("VOLVER AL MENÚ PRINCIPAL");
        btnVolverMV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDatosCompradorMV)
                            .addComponent(lblCarritoMV)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFormaDePagoMV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxFormaPagoMV, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTituloMV)
                                    .addComponent(lblCantidadMV)
                                    .addComponent(lblPrecioMV))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldPrecioMV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldCantidadMV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxTituloMV, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnVolverMV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarOrdenMV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTituloMantenedorVentas)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApellidoMaternoMV)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lvlNombreMV)
                                        .addComponent(lblApellidoPaternoMV))
                                    .addComponent(lblRUTMV, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelefonoMV, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDireccionMV, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldNombreMV)
                                    .addComponent(fieldApellidoPaternoMV)
                                    .addComponent(fieldApellidoMaternoMV)
                                    .addComponent(fieldRUTMV)
                                    .addComponent(fieldTelefonoMV)
                                    .addComponent(fieldDireccionMV, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloMantenedorVentas)
                .addGap(18, 18, 18)
                .addComponent(lblDatosCompradorMV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlNombreMV)
                    .addComponent(fieldNombreMV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoPaternoMV)
                    .addComponent(fieldApellidoPaternoMV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoMaternoMV)
                    .addComponent(fieldApellidoMaternoMV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRUTMV)
                    .addComponent(fieldRUTMV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoMV)
                    .addComponent(fieldTelefonoMV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionMV)
                    .addComponent(fieldDireccionMV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblCarritoMV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloMV)
                    .addComponent(comboBoxTituloMV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadMV)
                    .addComponent(fieldCantidadMV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioMV)
                    .addComponent(fieldPrecioMV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaDePagoMV)
                    .addComponent(comboBoxFormaPagoMV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarOrdenMV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolverMV, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void fieldCantidadMVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCantidadMVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCantidadMVActionPerformed

    private void btnGenerarOrdenMVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarOrdenMVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarOrdenMVActionPerformed

    private void btnVolverMVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMVActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverMVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVenderLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVenderLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVenderLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVenderLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVenderLibros().setVisible(true);
            }
        });
    }
    
        public void cerrar()
    {
        int resp=JOptionPane.showConfirmDialog(null,"¿Esta seguro/a que desea cerrar la ventana de Vender Libros?","Confirmación de Cierre",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(resp==JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarOrdenMV;
    private javax.swing.JButton btnVolverMV;
    private javax.swing.JComboBox<String> comboBoxFormaPagoMV;
    private javax.swing.JComboBox<String> comboBoxTituloMV;
    private javax.swing.JTextField fieldApellidoMaternoMV;
    private javax.swing.JTextField fieldApellidoPaternoMV;
    private javax.swing.JTextField fieldCantidadMV;
    private javax.swing.JTextField fieldDireccionMV;
    private javax.swing.JTextField fieldNombreMV;
    private javax.swing.JTextField fieldPrecioMV;
    private javax.swing.JTextField fieldRUTMV;
    private javax.swing.JTextField fieldTelefonoMV;
    private javax.swing.JLabel lblApellidoMaternoMV;
    private javax.swing.JLabel lblApellidoPaternoMV;
    private javax.swing.JLabel lblCantidadMV;
    private javax.swing.JLabel lblCarritoMV;
    private javax.swing.JLabel lblDatosCompradorMV;
    private javax.swing.JLabel lblDireccionMV;
    private javax.swing.JLabel lblFormaDePagoMV;
    private javax.swing.JLabel lblPrecioMV;
    private javax.swing.JLabel lblRUTMV;
    private javax.swing.JLabel lblTelefonoMV;
    private javax.swing.JLabel lblTituloMV;
    private javax.swing.JLabel lblTituloMantenedorVentas;
    private javax.swing.JLabel lvlNombreMV;
    // End of variables declaration//GEN-END:variables
}
