package Vistas;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tomas
 */
public class FormLibros extends javax.swing.JFrame {

    /**
     * Creates new form FormLibros
     */
    public FormLibros() {
        initComponents();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloMantenedorLibros = new javax.swing.JLabel();
        panelMantenedorLibros = new javax.swing.JPanel();
        lblNdeSerieML = new javax.swing.JLabel();
        lblISBNML = new javax.swing.JLabel();
        lblTituloML = new javax.swing.JLabel();
        lblNdePaginasML = new javax.swing.JLabel();
        lblPrecioML = new javax.swing.JLabel();
        lblAñoPubliML = new javax.swing.JLabel();
        lblEstadoML = new javax.swing.JLabel();
        fieldNumeroSerieML = new javax.swing.JTextField();
        fieldISBNML = new javax.swing.JTextField();
        fieldTituloML = new javax.swing.JTextField();
        fieldNroPaginasML = new javax.swing.JTextField();
        fieldPrecioML = new javax.swing.JTextField();
        fieldAñoPubliML = new javax.swing.JTextField();
        comboBoxEstadoML = new javax.swing.JComboBox<>();
        lblEditorialML = new javax.swing.JLabel();
        lblAutorML = new javax.swing.JLabel();
        fieldEditorialML = new javax.swing.JTextField();
        fieldAutorML = new javax.swing.JTextField();
        btnINGRESARML = new javax.swing.JButton();
        btnBUSCARML = new javax.swing.JButton();
        btnELIMINARML = new javax.swing.JButton();
        btnLIMPIARML = new javax.swing.JButton();
        btnVolverML = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MANTENEDOR DE LIBROS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTituloMantenedorLibros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTituloMantenedorLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/libros.png"))); // NOI18N
        lblTituloMantenedorLibros.setText("MANTENEDOR DE LIBROS");

        lblNdeSerieML.setText("Número de serie :");

        lblISBNML.setText("ISBN :");

        lblTituloML.setText("Título :");

        lblNdePaginasML.setText("Nro. Páginas :");

        lblPrecioML.setText("Precio :");

        lblAñoPubliML.setText("Año publicación :");

        lblEstadoML.setText("Estado :");

        fieldNumeroSerieML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumeroSerieMLActionPerformed(evt);
            }
        });

        comboBoxEstadoML.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));

        lblEditorialML.setText("Editorial :");

        lblAutorML.setText("Autor :");

        fieldAutorML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAutorMLActionPerformed(evt);
            }
        });

        btnINGRESARML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/log-in ESTE OCUPÉ.png"))); // NOI18N
        btnINGRESARML.setText("INGRESAR");

        btnBUSCARML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/browse.png"))); // NOI18N
        btnBUSCARML.setText("BUSCAR");

        btnELIMINARML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eliminar.png"))); // NOI18N
        btnELIMINARML.setText("ELIMINAR");

        btnLIMPIARML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpiar.png"))); // NOI18N
        btnLIMPIARML.setText("LIMPIAR");
        btnLIMPIARML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIMPIARMLActionPerformed(evt);
            }
        });

        btnVolverML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/regreso.png"))); // NOI18N
        btnVolverML.setText("VOLVER AL MENÚ PRINCIPAL");
        btnVolverML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMantenedorLibrosLayout = new javax.swing.GroupLayout(panelMantenedorLibros);
        panelMantenedorLibros.setLayout(panelMantenedorLibrosLayout);
        panelMantenedorLibrosLayout.setHorizontalGroup(
            panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantenedorLibrosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMantenedorLibrosLayout.createSequentialGroup()
                        .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelMantenedorLibrosLayout.createSequentialGroup()
                                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnELIMINARML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBUSCARML, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnINGRESARML, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLIMPIARML, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnVolverML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(panelMantenedorLibrosLayout.createSequentialGroup()
                        .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrecioML)
                            .addComponent(lblTituloML)
                            .addComponent(lblNdeSerieML)
                            .addComponent(lblISBNML)
                            .addComponent(lblNdePaginasML)
                            .addComponent(lblEstadoML)
                            .addComponent(lblEditorialML)
                            .addComponent(lblAutorML)
                            .addComponent(lblAñoPubliML))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldISBNML)
                            .addComponent(fieldTituloML)
                            .addComponent(fieldNroPaginasML)
                            .addComponent(fieldPrecioML)
                            .addComponent(fieldAñoPubliML)
                            .addComponent(fieldNumeroSerieML)
                            .addComponent(comboBoxEstadoML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldEditorialML)
                            .addComponent(fieldAutorML, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelMantenedorLibrosLayout.setVerticalGroup(
            panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMantenedorLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNdeSerieML)
                    .addComponent(fieldNumeroSerieML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblISBNML)
                    .addComponent(fieldISBNML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloML)
                    .addComponent(fieldTituloML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNdePaginasML)
                    .addComponent(fieldNroPaginasML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioML)
                    .addComponent(fieldPrecioML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAñoPubliML)
                    .addComponent(fieldAñoPubliML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxEstadoML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoML))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditorialML)
                    .addComponent(fieldEditorialML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutorML)
                    .addComponent(fieldAutorML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBUSCARML)
                    .addComponent(btnINGRESARML))
                .addGap(18, 18, 18)
                .addGroup(panelMantenedorLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnELIMINARML)
                    .addComponent(btnLIMPIARML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolverML)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblTituloMantenedorLibros)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMantenedorLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloMantenedorLibros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMantenedorLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void btnLIMPIARMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIMPIARMLActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLIMPIARMLActionPerformed

    private void fieldAutorMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAutorMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAutorMLActionPerformed

    private void fieldNumeroSerieMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumeroSerieMLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumeroSerieMLActionPerformed

    private void btnVolverMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMLActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLibros().setVisible(true);
            }
        });
    }
    public void limpiar()
    {
         fieldAutorML.setText("");
         fieldAñoPubliML.setText("");
         fieldEditorialML.setText("");
         fieldISBNML.setText("");
         fieldNroPaginasML.setText("");
         fieldPrecioML.setText("");
         fieldTituloML.setText("");
         fieldNumeroSerieML.setText("");
        
         
         
         btnELIMINARML.setEnabled(false);
         btnBUSCARML.setEnabled(false);
         
         fieldNumeroSerieML.requestFocus();
    }
    
        public void cerrar()
    {
        int resp=JOptionPane.showConfirmDialog(null,"¿Esta seguro/a que desea cerrar la ventana de Libros?","Confirmación de Cierre",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(resp==JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBUSCARML;
    private javax.swing.JButton btnELIMINARML;
    private javax.swing.JButton btnINGRESARML;
    private javax.swing.JButton btnLIMPIARML;
    private javax.swing.JButton btnVolverML;
    private javax.swing.JComboBox<String> comboBoxEstadoML;
    private javax.swing.JTextField fieldAutorML;
    private javax.swing.JTextField fieldAñoPubliML;
    private javax.swing.JTextField fieldEditorialML;
    private javax.swing.JTextField fieldISBNML;
    private javax.swing.JTextField fieldNroPaginasML;
    private javax.swing.JTextField fieldNumeroSerieML;
    private javax.swing.JTextField fieldPrecioML;
    private javax.swing.JTextField fieldTituloML;
    private javax.swing.JLabel lblAutorML;
    private javax.swing.JLabel lblAñoPubliML;
    private javax.swing.JLabel lblEditorialML;
    private javax.swing.JLabel lblEstadoML;
    private javax.swing.JLabel lblISBNML;
    private javax.swing.JLabel lblNdePaginasML;
    private javax.swing.JLabel lblNdeSerieML;
    private javax.swing.JLabel lblPrecioML;
    private javax.swing.JLabel lblTituloML;
    private javax.swing.JLabel lblTituloMantenedorLibros;
    private javax.swing.JPanel panelMantenedorLibros;
    // End of variables declaration//GEN-END:variables
}
