package Vistas;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tomas
 */
public class FormAutor extends javax.swing.JFrame {

    /**
     * Creates new form FormAutor
     */
    public FormAutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldNacionalidadMA = new javax.swing.JTextField();
        lblNacionalidadMA = new javax.swing.JLabel();
        lblOtrosTitulosMA = new javax.swing.JLabel();
        fieldOtrosTitulosMA = new javax.swing.JTextField();
        lblSexoMA = new javax.swing.JLabel();
        comboBoxSexoMA = new javax.swing.JComboBox<>();
        lblNombreMA = new javax.swing.JLabel();
        lblApellidoMaternoMA = new javax.swing.JLabel();
        fieldNombreMA = new javax.swing.JTextField();
        fieldApellidoMA = new javax.swing.JTextField();
        lblTituloMA = new javax.swing.JLabel();
        lblCodAutorMA = new javax.swing.JLabel();
        fieldCodigoAutorMA = new javax.swing.JTextField();
        btnINGRESARMA = new javax.swing.JButton();
        btnLIMPIARMA = new javax.swing.JButton();
        lblApellidoPaternoMA = new javax.swing.JLabel();
        fieldApellidoPaternoMA = new javax.swing.JTextField();
        btnVolverMA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("BUSCADOR DE AUTORES");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNacionalidadMA.setText("Nacionalidad:");

        lblOtrosTitulosMA.setText("Otros títulos:");

        lblSexoMA.setText("Sexo:");

        comboBoxSexoMA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "No Binario" }));

        lblNombreMA.setText("Nombre:");

        lblApellidoMaternoMA.setText("Apellido Materno:");

        fieldNombreMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreMAActionPerformed(evt);
            }
        });

        lblTituloMA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloMA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/escritor.png"))); // NOI18N
        lblTituloMA.setText("MANTENEDOR DE AUTORES");

        lblCodAutorMA.setText("Código Autor:");

        btnINGRESARMA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/log-in ESTE OCUPÉ.png"))); // NOI18N
        btnINGRESARMA.setText("INGRESAR");
        btnINGRESARMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnINGRESARMAActionPerformed(evt);
            }
        });

        btnLIMPIARMA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpiar.png"))); // NOI18N
        btnLIMPIARMA.setText("LIMPIAR");
        btnLIMPIARMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLIMPIARMAActionPerformed(evt);
            }
        });

        lblApellidoPaternoMA.setText("Apellido Paterno:");

        fieldApellidoPaternoMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldApellidoPaternoMAActionPerformed(evt);
            }
        });

        btnVolverMA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/regreso.png"))); // NOI18N
        btnVolverMA.setText("VOLVER AL MENÚ PRINCIPAL");
        btnVolverMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblApellidoMaternoMA)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNacionalidadMA)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSexoMA)
                            .addComponent(lblOtrosTitulosMA)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodAutorMA)
                        .addGap(1, 1, 1))
                    .addComponent(lblNombreMA)
                    .addComponent(lblApellidoPaternoMA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldNacionalidadMA)
                    .addComponent(fieldApellidoMA)
                    .addComponent(fieldNombreMA)
                    .addComponent(fieldApellidoPaternoMA)
                    .addComponent(fieldOtrosTitulosMA)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(comboBoxSexoMA, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldCodigoAutorMA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 233, Short.MAX_VALUE)
                .addComponent(lblTituloMA)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnINGRESARMA, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLIMPIARMA, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolverMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloMA)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreMA)
                    .addComponent(fieldNombreMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoMaternoMA)
                    .addComponent(fieldApellidoMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldApellidoPaternoMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidoPaternoMA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNacionalidadMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNacionalidadMA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOtrosTitulosMA)
                    .addComponent(fieldOtrosTitulosMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxSexoMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexoMA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCodigoAutorMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodAutorMA))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnINGRESARMA)
                    .addComponent(btnLIMPIARMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVolverMA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreMAActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void btnINGRESARMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnINGRESARMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnINGRESARMAActionPerformed

    private void btnLIMPIARMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLIMPIARMAActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLIMPIARMAActionPerformed

    private void fieldApellidoPaternoMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldApellidoPaternoMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldApellidoPaternoMAActionPerformed

    private void btnVolverMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMAActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverMAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAutor().setVisible(true);
            }
        });
    }
    public void limpiar()
    {
         fieldNombreMA.setText("");
         fieldApellidoMA.setText("");
         fieldNacionalidadMA.setText("");
         fieldOtrosTitulosMA.setText("");
         fieldCodigoAutorMA.setText("");
      
         
         fieldNombreMA.requestFocus();
    }
    
        public void cerrar()
    {
        int resp=JOptionPane.showConfirmDialog(null,"¿Esta seguro/a que desea cerrar la ventana de Autor?","Confirmación de Cierre",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(resp==JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnINGRESARMA;
    private javax.swing.JButton btnLIMPIARMA;
    private javax.swing.JButton btnVolverMA;
    private javax.swing.JComboBox<String> comboBoxSexoMA;
    private javax.swing.JTextField fieldApellidoMA;
    private javax.swing.JTextField fieldApellidoPaternoMA;
    private javax.swing.JTextField fieldCodigoAutorMA;
    private javax.swing.JTextField fieldNacionalidadMA;
    private javax.swing.JTextField fieldNombreMA;
    private javax.swing.JTextField fieldOtrosTitulosMA;
    private javax.swing.JLabel lblApellidoMaternoMA;
    private javax.swing.JLabel lblApellidoPaternoMA;
    private javax.swing.JLabel lblCodAutorMA;
    private javax.swing.JLabel lblNacionalidadMA;
    private javax.swing.JLabel lblNombreMA;
    private javax.swing.JLabel lblOtrosTitulosMA;
    private javax.swing.JLabel lblSexoMA;
    private javax.swing.JLabel lblTituloMA;
    // End of variables declaration//GEN-END:variables
}
