package Vistas;

import Controlador.ControladorEditorial;
import Controlador.ControladorUsuarios;
import Modelo.CrudEditorial;
import Modelo.CrudUsuarios;
import Modelo.Editorial;
import Modelo.Usuarios;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tomas
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        btnFormUsuariosMP = new javax.swing.JButton();
        btnFormAutoresMP = new javax.swing.JButton();
        btnFormIdiomasMP = new javax.swing.JButton();
        btnFormCategoriasMP = new javax.swing.JButton();
        btnFormArrendarLibrosMP = new javax.swing.JButton();
        btnFormLibrosMP = new javax.swing.JButton();
        btnFormEditorialesMP = new javax.swing.JButton();
        btnFormVenderLibrosMP = new javax.swing.JButton();
        btnDevolverLibrosMP = new javax.swing.JButton();
        btnSalirDelSistemaMP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblIconMP = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        jPasswordField2.setText("jPasswordField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("MENU PRINCIPAL DE ACCESO A MODULOS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnFormUsuariosMP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFormUsuariosMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/equipo.png"))); // NOI18N
        btnFormUsuariosMP.setText("Mantenedor de Usuarios");
        btnFormUsuariosMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormUsuariosMPActionPerformed(evt);
            }
        });

        btnFormAutoresMP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFormAutoresMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/escritor.png"))); // NOI18N
        btnFormAutoresMP.setText("Mantenedor de Autores");
        btnFormAutoresMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormAutoresMPActionPerformed(evt);
            }
        });

        btnFormIdiomasMP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFormIdiomasMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/idiomas.png"))); // NOI18N
        btnFormIdiomasMP.setText("Mantenedor de Idiomas");
        btnFormIdiomasMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormIdiomasMPActionPerformed(evt);
            }
        });

        btnFormCategoriasMP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFormCategoriasMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/contenido.png"))); // NOI18N
        btnFormCategoriasMP.setText("Mantenedor de Categorias");
        btnFormCategoriasMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormCategoriasMPActionPerformed(evt);
            }
        });

        btnFormArrendarLibrosMP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFormArrendarLibrosMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trato.png"))); // NOI18N
        btnFormArrendarLibrosMP.setText("Arrendar Libros");
        btnFormArrendarLibrosMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormArrendarLibrosMPActionPerformed(evt);
            }
        });

        btnFormLibrosMP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFormLibrosMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/libros.png"))); // NOI18N
        btnFormLibrosMP.setText("Mantenedor de Libros");
        btnFormLibrosMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormLibrosMPActionPerformed(evt);
            }
        });

        btnFormEditorialesMP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFormEditorialesMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/editorial.png"))); // NOI18N
        btnFormEditorialesMP.setText("Mantenedor de Editoriales");
        btnFormEditorialesMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormEditorialesMPActionPerformed(evt);
            }
        });

        btnFormVenderLibrosMP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFormVenderLibrosMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dinero.png"))); // NOI18N
        btnFormVenderLibrosMP.setText("Vender Libros");
        btnFormVenderLibrosMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormVenderLibrosMPActionPerformed(evt);
            }
        });

        btnDevolverLibrosMP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDevolverLibrosMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/leyendo.png"))); // NOI18N
        btnDevolverLibrosMP.setText("Devolver Libros");
        btnDevolverLibrosMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverLibrosMPActionPerformed(evt);
            }
        });

        btnSalirDelSistemaMP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalirDelSistemaMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/salida-de-emergencia.png"))); // NOI18N
        btnSalirDelSistemaMP.setText("Salir del Sistema");
        btnSalirDelSistemaMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirDelSistemaMPActionPerformed(evt);
            }
        });

        lblIconMP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/libro (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFormLibrosMP, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFormCategoriasMP))
                        .addGap(44, 44, 44)
                        .addComponent(lblIconMP, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFormArrendarLibrosMP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDevolverLibrosMP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFormUsuariosMP, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFormVenderLibrosMP, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFormIdiomasMP, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalirDelSistemaMP, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFormAutoresMP, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFormEditorialesMP, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(485, 485, 485)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblIconMP))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFormUsuariosMP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFormVenderLibrosMP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFormArrendarLibrosMP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDevolverLibrosMP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFormLibrosMP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFormCategoriasMP, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFormAutoresMP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(btnFormEditorialesMP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormIdiomasMP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirDelSistemaMP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFormUsuariosMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormUsuariosMPActionPerformed
        // TODO add your handling code here:
        Usuarios usu=new Usuarios();
        FormUsuario frm=new FormUsuario();
        CrudUsuarios cons=new CrudUsuarios();
        ControladorUsuarios ctrl=new ControladorUsuarios(frm,cons,usu);
        
        ctrl.iniciar();
        frm.setVisible(true);
       
    }//GEN-LAST:event_btnFormUsuariosMPActionPerformed

    private void btnFormAutoresMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormAutoresMPActionPerformed
        // TODO add your handling code here:
        FormAutor autor=new FormAutor();
        autor.setVisible(true);
        autor.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnFormAutoresMPActionPerformed

    private void btnFormIdiomasMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormIdiomasMPActionPerformed
        // TODO add your handling code here:
        FormIdiomas idioma=new FormIdiomas();
        idioma.setVisible(true);
        idioma.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnFormIdiomasMPActionPerformed

    private void btnSalirDelSistemaMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirDelSistemaMPActionPerformed
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_btnSalirDelSistemaMPActionPerformed

    private void btnDevolverLibrosMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverLibrosMPActionPerformed
        // TODO add your handling code here:
        FormDevolverLibros devolverL=new FormDevolverLibros();
        devolverL.setVisible(true);
        devolverL.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnDevolverLibrosMPActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void btnFormEditorialesMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormEditorialesMPActionPerformed
        // TODO add your handling code here:
        Editorial edit=new Editorial();
        FormEditorial frm=new FormEditorial();
        CrudEditorial cons=new CrudEditorial();
        ControladorEditorial ctrl=new ControladorEditorial(edit,cons,frm);
        
        ctrl.iniciar();
        frm.setVisible(true);
    }//GEN-LAST:event_btnFormEditorialesMPActionPerformed

    private void btnFormArrendarLibrosMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormArrendarLibrosMPActionPerformed
        // TODO add your handling code here:
        FormArrendarLibros arriendo=new FormArrendarLibros();
        arriendo.setVisible(true);
        arriendo.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnFormArrendarLibrosMPActionPerformed

    private void btnFormCategoriasMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormCategoriasMPActionPerformed
        // TODO add your handling code here:
        FormCategoria categoria=new FormCategoria();
        categoria.setVisible(true);
        categoria.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnFormCategoriasMPActionPerformed

    private void btnFormLibrosMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormLibrosMPActionPerformed
        // TODO add your handling code here:
        FormLibros libro=new FormLibros();
        libro.setVisible(true);
        libro.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnFormLibrosMPActionPerformed

    private void btnFormVenderLibrosMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormVenderLibrosMPActionPerformed
        // TODO add your handling code here:
        FormVenderLibros ventaLibro=new FormVenderLibros();
        ventaLibro.setVisible(true);
        ventaLibro.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnFormVenderLibrosMPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    public void cerrar()
    {
        int resp=JOptionPane.showConfirmDialog(null,"¿Esta seguro/a que desea salir del sistema?","Confirmación de Cierre",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        
        if(resp==JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }  
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolverLibrosMP;
    private javax.swing.JButton btnFormArrendarLibrosMP;
    private javax.swing.JButton btnFormAutoresMP;
    private javax.swing.JButton btnFormCategoriasMP;
    private javax.swing.JButton btnFormEditorialesMP;
    private javax.swing.JButton btnFormIdiomasMP;
    private javax.swing.JButton btnFormLibrosMP;
    private javax.swing.JButton btnFormUsuariosMP;
    private javax.swing.JButton btnFormVenderLibrosMP;
    private javax.swing.JButton btnSalirDelSistemaMP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel lblIconMP;
    // End of variables declaration//GEN-END:variables
}
